### ISSUE TITLE
Not able to use the plugin

### ISSUE THREAD

**Issue by gitbro23** [V4n1X/check-apc-usv#1]
To use the plugin I need to know which parameters are necessary. Like "host" or "IP" or what ever. So from my point of view without these "usage" information I'm not able to use it.

I already tried a little but without success.

When I start the script like that:
`php /lib/nagios/plugins/check_apc_usv.php`

The output is:
```
PHP Notice:  Undefined offset: 1 in /usr/lib/nagios/plugins/check_apc_usv.php on line 11
PHP Fatal error:  Uncaught Error: Call to undefined function snmpget() in /usr/lib/nagios/plugins/check_apc_usv.php:19
Stack trace:
#0 {main}
  thrown in /usr/lib/nagios/plugins/check_apc_usv.php on line 19
```

When I add the hostname after the script like that
`php /lib/nagios/plugins/check_apc_usv.php hostname.domain.tld`

The output is:
```
PHP Fatal error:  Uncaught Error: Call to undefined function snmpget() in /usr/lib/nagios/plugins/check_apc_usv.php:19
Stack trace:
#0 {main}
  thrown in /usr/lib/nagios/plugins/check_apc_usv.php on line 19
```

The same is when I type it like that:
`php /lib/nagios/plugins/check_apc_usv.php -host hostname.domain.tld`
or
`php /lib/nagios/plugins/check_apc_usv.php -host=hostname.domain.tld`
or
`php /lib/nagios/plugins/check_apc_usv.php host=hostname.domain.tld`

So please help me to use the right parameters

Thanks in advance

**Comment by Fabrisus** [comment]
You need php-snmp otherwise the function snmpget wont work.

**Comment by gitbro23** [comment]
Great!! Now its OK!
`php /lib/nagios/plugins/check_apc_usv.php hostname.domain.tld`

But I also edit the script and add in the first row:
`#!/usr/bin/php -q`

Thank you so much!!
